name: misstory
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # sqflite: ^1.1.6+1                #数据库包
  json_annotation: ^3.0.0      #json包
#  flutter_amap_location_plugin:    #定位插件包
#    git:
#      url: https://github.com/FIRHQ/flutter_amap_location_plugin.git

  lifecycle_state: ^0.0.1
  intl: ^0.15.8
#  permission_handler: ^3.2.2
  #  amap_base_map:
  #    git:
  #      url: https://github.com/tianyu704/amap_base_flutter.git
  #      path: 'map'
  #  amap_base_search:
  #    git:
  #      url: https://github.com/tianyu704/amap_base_flutter.git
  #      path: 'search'

#  amap_base:
#    git:
#      url: https://github.com/tianyu704/amap_base_flutter.git
#      path: 'base'

  flutter_orm_plugin: 1.0.13
  grouped_listview: ^0.0.2 #分组包
  provider: ^3.1.0
  shared_preferences: 0.5.3+4
  full_icon_button: ^0.0.1+3
  #fluttertoast: ^3.1.3
  flutter_svg: 0.14.2
  pull_to_refresh: ^1.5.7
  loading_indicator: ^1.1.0
  local_image_provider:
    git:
      url: https://github.com/tianyu704/local_image_provider.git
  #  flutter_image_compress: ^0.6.3
  extended_image: ^0.6.4 #图片展示
#  flutter_image_compress: 0.6.3 #图片压缩
  event_bus: ^1.1.0
  dio: ^2.1.8
#  connectivity: ^0.4.5+2
  uuid: ^2.0.2
#  firebase_crashlytics: 0.1.1+2
  flutter_bugly: 0.2.8
 # 获取包名版本号信息
  package_info: ^0.4.0+2
  webview_flutter:
    git:
      url: https://github.com/shaqian/plugins.git
      path: 'packages/webview_flutter'
      ref: shaqian/webview
dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.0.0         #json开发依赖 是开发过程中的一些辅助工具、脚本
  json_serializable: ^3.2.3    #json开发依赖 是开发过程中的一些辅助工具、脚本 它是一个自动化的源代码生成器，可以在开发阶段为我们生成JSON序列化模板，这样一来，由于序列化代码不再由我们手写和维护，我们将运行时产生JSON序列化异常的风险降至最低。
#  json_model: ^0.0.2           #json开发依赖 是开发过程中的一些辅助工具、脚本
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # flutter_orm_plugin assets
    - packages/flutter_orm_plugin/lua/DB.lua
    - packages/flutter_orm_plugin/lua/orm/model.lua
    - packages/flutter_orm_plugin/lua/orm/cache.lua
    - packages/flutter_orm_plugin/lua/orm/dbData.lua
    - packages/flutter_orm_plugin/lua/orm/tools/fields.lua
    - packages/flutter_orm_plugin/lua/orm/tools/func.lua
    - packages/flutter_orm_plugin/lua/orm/class/fields.lua
    - packages/flutter_orm_plugin/lua/orm/class/global.lua
    - packages/flutter_orm_plugin/lua/orm/class/property.lua
    - packages/flutter_orm_plugin/lua/orm/class/query.lua
    - packages/flutter_orm_plugin/lua/orm/class/query_list.lua
    - packages/flutter_orm_plugin/lua/orm/class/select.lua
    - packages/flutter_orm_plugin/lua/orm/class/table.lua
    - packages/flutter_orm_plugin/lua/orm/class/type.lua
    # svg image
    - assets/images/
    - assets/images/icon_location_fill.svg
    - assets/images/icon_location_empty.svg
    - assets/images/icon_location_delete.svg
    - assets/images/icon_remain_time.svg
    - assets/images/icon_search.svg
    - assets/images/icon_poi_item.svg
    - assets/images/icon_poi_none.svg
    - assets/images/icon_edit.svg
    - assets/images/icon_back.svg
    - assets/images/icon_picture_process.svg
      # images
    - assets/images/
    - assets/images/icon_loading_picture_star.png
    - assets/images/icon_location.png
    #html
    - assets/html/tencent_map.html
    - assets/html/google_map.html
    - assets/html/gaode_map.html
    - assets/html/mapbox_map.html
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,

  # see https://flutter.dev/custom-fonts/#from-packages
